---
- name: Clone the repository
  git:
    repo: "https://github.com/internetkultur-ab/ipsw-downloader.git"
    dest: ~/git/ipsw-downloader
    version: master

- name: Install pip package 'requests' inside the cloned repository
  pip:
    name: requests
    virtualenv: "~/git/ipsw-downloader/.venv"
    virtualenv_command: /opt/homebrew/bin/python3 -m venv
    state: present

- name: Verify installation of 'requests'
  command: "~/git/ipsw-downloader/.venv/bin/pip show requests"
  register: pip_show_result

- name: Debug output of 'requests' installation
  debug:
    var: pip_show_result.stdout

- name: Create a cronjob
  ansible.builtin.cron:
    name: "run ipsw-downloader"
    minute: "0"
    hour: "2"
    job: "~/git/ipsw-downloader/.venv/bin/python3 ~/git/ipsw-downloader/ipsw-downloader.py > /dev/null 2>&1"
